# Generated by Django 4.2.1 on 2023-05-13 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.CharField(blank=True, max_length=250)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('img', models.CharField(blank=True, max_length=250)),
                ('brand', models.CharField(blank=True, max_length=250)),
                ('price', models.IntegerField(blank=True)),
                ('screenSize', models.CharField(blank=True, max_length=250)),
                ('memoryCard', models.CharField(blank=True, max_length=250)),
                ('cpu', models.CharField(blank=True, max_length=250)),
                ('videoCard', models.CharField(blank=True, max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
